### ISSUE TITLE
无法使用问题

### ISSUE THREAD

**Issue by Ahuangshang** [bingo-oss/bui-weex#10]
按照你们官方步骤新建项目后，在执行npm run dev时一直不成功，为什么？

**Comment by Ahuangshang** [comment]
一直说bui-weex-template@1.0.0 license should be a valid SPDX license expression

**Comment by tonyyls** [comment]
这个错误大概意思是没有合法的license，可以尝试将package.json里面的license字段去掉，这个按理是不影响框架的正常运行的

**Comment by Ahuangshang** [comment]
按照你说的删掉了license字段，然后报如下错误
npm WARN sass-loader@6.0.6 requires a peer of webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0 but none was installed.
npm WARN bui-weex-template@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
怎么样才能安装上

**Comment by Ahuangshang** [comment]
把package.json里面的 "sass-loader改为"sass-loader": "^6.0.6",就可以了，但是为什么每次build后只生成app.**.js,其他文件不会生成js文件，该如何配置？

**Comment by tonyyls** [comment]
回答上面两个疑问：
1.warn级别的无需理会的；
2.dist下会生成js, image, font 等资源。 为啥只有app.**.js 呢？ 它是由 webpack.config.js 决定的，里面会遍历 src/entry的 入口js，在此声明了才会最后build出来成为 bundle js。  可以看看 文档关于目录规范这一章节。

**Comment by Ahuangshang** [comment]
两个问题：
1.如何更改预览主界面，不是网页预览那个，手机扫码预览；
2.使用的是2.0写的吗？我先前用2.0写的项目导入你们库后，编译出的js显示不出来。

**Comment by tonyyls** [comment]
1.入口页面在 src/entry/app.js ，里面有告诉你指向哪个 vue 页面（src/views/app.vue）；
2.基于 weexsdk 0.11.0+, vue 2.0 , weex 2.x
先按照文档，可以先简单的在页面添加几个组件 看看效果，再尝试跟你现有的东西做整合集成。

**Comment by tonyyls** [comment]
另外， 可以看看 sample

**Comment by Ahuangshang** [comment]
debug发现在加载js文件是会报错：createInstanceSyntaxError: Unexpected reserved word，errorCode是-2013

**Comment by tonyyls** [comment]
这个看上去是weex底层报出来的，能定位到具体哪个组件出的问题吗？或者发一个 可以访问到的 js地址出来，我这边用playground 试试

**Comment by Ahuangshang** [comment]
都没用你们的控件，就是我先前写的界面，通过你们这个方式build出来的js文件一加载就报这个错，但是如果用weex compile编译出的js文件就不会，不知道哪里出了问题了

**Comment by tonyyls** [comment]
这样估计是你的界面用到的一些语法不兼容导致的。 方便的话可以将你的源码发一份到网盘共享给我帮你看一眼。

**Comment by Ahuangshang** [comment]
我知道问题的原因了，就是在entry目录下的.js文件是我自己写的，如下：
import App from '../views/app.vue'
import mixins from '../js/mixins'
Vue.mixin(mixins);
App.el = '#root'

new Vue(App)
点击第一行的App时不能跳转，你们的demo是可以跳转到对应的页面的，而且名字可以随便改，为什么我的不行呢？这里面的文件是要生成吗？
