### ISSUE TITLE
createInstanceException: SyntaxError: Unexpected identifier 'Login'. import call expects exactly one argument.

### ISSUE THREAD

**Issue by 15136356361** [bingo-oss/bui-weex#13]
createInstanceException: SyntaxError: Unexpected identifier 'Login'. import call expects exactly one argument. 求解这个是因为什么呢

**Comment by tonyyls** [comment]
框架里面似乎没有带Login的关键字，搜索Login在哪里出现

**Comment by 15136356361** [comment]
import Login from '../views/login.vue'
import mixins from '../js/mixins.js'

Vue.mixin(mixins);

Login.el = "#root"

new Vue(Login)  这个是我自己写的一个  加载页面时抱着个错 这个是语法问题吗 谢谢

**Comment by tonyyls** [comment]
你贴的代码没错，关键是login.vue里面看看。另外新增一个entry的js，要重新运行npm run dev

**Comment by 15136356361** [comment]
嗯  你说的我都新增了  也重新运行了  那就可能是login.vue里面的问题了吧

**Comment by tonyyls** [comment]
是的，检查login.vue里面

**Comment by 15136356361** [comment]
<template>
    <div>
    <text class="loginbutton" >立即登录</text>
    </div>
</template>
<style lang="sass" src="bui-weex/src/css/buiweex.scss"></style>

<script>

    export default {
        
        data: function () {
            return {

            }
        }

    };
</script>我现在里面就这点东西了  为什么还是报那个错啊

**Comment by 15136356361** [comment]
问题已解决，谢啦
