### ISSUE TITLE
怎么在已经建好的weex项目中直接引入 bui-weex 

### ISSUE THREAD

**Issue by Yuamo** [bingo-oss/bui-weex#14]
如题怎么在已经建好的weex项目中直接引入 bui-weex ？

**Comment by tonyyls** [comment]
稍后会出指引文档，四点左右

**Comment by tonyyls** [comment]
已经增加相关指引文档，请移步 [《已有项目集成 BUI-Weex》](http://dev.bingocc.com/buiweex/docs/integration.html)

**Comment by Yuamo** [comment]
好的谢谢！
还有个问题想问下 ，文档推荐的独立页面+navigator 这个种方式还对Vuex支持吗？ 我之前的项目是 Vue-router + Vuex 来实现！
如果支持有什么要注意的地方吗？

**Comment by tonyyls** [comment]
不影响你使用Vue-router + Vuex

**Comment by Yuamo** [comment]
我想吧项目改成 独立页面+navigator 的方式，还能用Vuex 吗？
