### ISSUE TITLE
i18n国际化问题

### ISSUE THREAD

**Issue by wangzhenyu1260** [bingo-oss/bui-weex#16]
使用kazupon/vue-i18n解决国际化问题，这样会导致所有页面都要引入全量的资源（EN.js, ZH.js）。比如页面A只是用了A1，A2，A3，但引入EN.js, ZH.js文件是整个工程用的，这样编译.vue的文件的时候，就会把所有EN.js, ZH.js内容都编到这个.vue翻译后的文件里。最终就是每个.vue都要包含一份，加载时增加网络流量。这个问题有好的解决办法吗？

**Comment by tonyyls** [comment]
可以考虑将bundle资源存在设备本地，这样就不用每次去load
