### ISSUE TITLE
开发人员麻烦看过来

### ISSUE THREAD

**Issue by PerseveranceZ** [bingo-oss/bui-weex#27]
首先感谢bui能提供这么好的weex开发体验，文档也非常的完善，给weex开发者带来了很大的帮助
目前我们团队抽离了一套weex解决方案并已开源，
https://karynsong.gitbooks.io/weex-eros/content/
目前选定 集成bui的组件库进来
能否加我微信进群 
微信号：zheshao20
我们可以一起讨论下关于weex组件这块的问题

**Comment by tonyyls** [comment]
感谢关注！可以加本人QQ: 570519827  一起探讨！

**Comment by romantictravel** [comment]
weex-eros 什么狗屎玩意,改的四不像.
