### ISSUE TITLE
打包之后的问题

### ISSUE THREAD

**Issue by xinshani** [bingo-oss/bui-weex#28]
打包之后dist 里面并没有app.web.js 。但是weex.html引入了。用浏览器访问是空白的，用weex app 访问是有内容的

**Comment by xinshani** [comment]
这个应该是webpack config 的问题吧

**Comment by tonyyls** [comment]
webback.config.js 里面 有个 webConfig,和 weexConfig，export 的时候一起暴露出去即可。我们因为特殊用途，所以把webConfig 暂时给去掉了！改成下面即可：
`module.exports = [webConfig, weexConfig];`

**Comment by xinshani** [comment]
webback.config.js 中只有一个weexConfig，试图创建一个webConfig，再将它暴露不过我失败了。尴尬`//*.weex.js
var weexConfig = getBaseConfig();
weexConfig.output.filename = '[name].weex.js';
weexConfig.module.loaders[1].loaders.push('weex');

var webConfig = getBaseConfig()
webConfig.output.filename = '[name].web.js'
webConfig.module.rules[1].loaders.push('vue')


module.exports = [weexConfig, webConfig];`

**Comment by xinshani** [comment]
参考您这个bui-weex-sample里面的 webpack.config.js。也配置了一份，打包的时候还是不成功，报node_modules中的很多错，您确定这个版本可以跑起来吗？

**Comment by tonyyls** [comment]
你说的打包不太明白。 基于bui-template工程，能够让你在dist目录下生成对应的 bundleJS，see dist folder ，仅此而已。   如果你使用的是 weexpack 去打包的话 应该用的工程是 weex官方的带有原生能力的工程。 原生工程  +  bundleJS = > apk/iOS
