### ISSUE TITLE
BUI集成到已有项目，使用weex-toolkit命令报错。

### ISSUE THREAD

**Issue by myeveryheart** [bingo-oss/bui-weex#29]
weex -v
   v1.1.0-beta.6
 - weexpack : v0.4.7-beta.17
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.8

info weex JS bundle saved at /Users/m/.weex_tmp
ERR! [webpack errors]
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0253d4fa","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/actionsheet.scss
Module build failed:
.bui-actionsheet{
                ^
      Invalid CSS after ".bui-actionsheet{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/actionsheet.scss (line 3, column 18)
Error:
.bui-actionsheet{
                ^
      Invalid CSS after ".bui-actionsheet{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/actionsheet.scss (line 3, column 18)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0253d4fa","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/actionsheet.scss 4:14-507
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-5ce6e599","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/radio.scss
Module build failed:
.radio-box {
           ^
      Invalid CSS after ".radio-box {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/radio.scss (line 3, column 13)
Error:
.radio-box {
           ^
      Invalid CSS after ".radio-box {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/radio.scss (line 3, column 13)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-5ce6e599","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/radio.scss 4:14-501
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-acc48df0","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/button.scss
Module build failed:
.btn {
     ^
      Invalid CSS after ".btn {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/button.scss (line 3, column 7)
Error:
.btn {
     ^
      Invalid CSS after ".btn {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/button.scss (line 3, column 7)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-acc48df0","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/button.scss 4:14-502
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-04b18915","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/radio.scss
Module build failed:
.radio-box {
           ^
      Invalid CSS after ".radio-box {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/radio.scss (line 3, column 13)
Error:
.radio-box {
           ^
      Invalid CSS after ".radio-box {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/radio.scss (line 3, column 13)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-04b18915","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/radio.scss 4:14-501
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7f8b780a","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/radio.scss
Module build failed:
.radio-box {
           ^
      Invalid CSS after ".radio-box {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/radio.scss (line 3, column 13)
Error:
.radio-box {
           ^
      Invalid CSS after ".radio-box {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/radio.scss (line 3, column 13)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7f8b780a","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/radio.scss 4:14-501
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-41b0941e","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/dialog.scss
Module build failed:
.bui-dialog-layout {
                   ^
      Invalid CSS after "...dialog-layout {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/dialog.scss (line 7, column 21)
Error:
.bui-dialog-layout {
                   ^
      Invalid CSS after "...dialog-layout {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/dialog.scss (line 7, column 21)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-41b0941e","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/dialog.scss 4:14-502
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0a1d4ee3","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/header.scss
Module build failed:
.bui-header-box{
               ^
      Invalid CSS after ".bui-header-box{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/header.scss (line 7, column 17)
Error:
.bui-header-box{
               ^
      Invalid CSS after ".bui-header-box{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/header.scss (line 7, column 17)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0a1d4ee3","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/header.scss 4:14-502
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-2d8236e7","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/dropdown.scss
Module build failed:
.bui-dropdown{
             ^
      Invalid CSS after ".bui-dropdown{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/dropdown.scss (line 3, column 15)
Error:
.bui-dropdown{
             ^
      Invalid CSS after ".bui-dropdown{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/dropdown.scss (line 3, column 15)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-2d8236e7","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/dropdown.scss 4:14-504
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-5f71543c","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/loading.scss
Module build failed:
.load-layout {
             ^
      Invalid CSS after ".load-layout {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/loading.scss (line 8, column 15)
Error:
.load-layout {
             ^
      Invalid CSS after ".load-layout {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/loading.scss (line 8, column 15)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-5f71543c","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/loading.scss 4:14-503
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-01d52342","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/mask.scss
Module build failed:
.bui-mask{
         ^
      Invalid CSS after ".bui-mask{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/mask.scss (line 4, column 11)
Error:
.bui-mask{
         ^
      Invalid CSS after ".bui-mask{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/mask.scss (line 4, column 11)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-01d52342","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/mask.scss 4:14-500
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-33ad5ac4","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/panel.scss
Module build failed:
.panel {
       ^
      Invalid CSS after ".panel {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/panel.scss (line 3, column 9)
Error:
.panel {
       ^
      Invalid CSS after ".panel {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/panel.scss (line 3, column 9)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-33ad5ac4","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/panel.scss 4:14-501
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-f9ed1666","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/layout.scss
Module build failed:
.flex-row{
         ^
      Invalid CSS after ".flex-row{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/layout.scss (line 5, column 11)
Error:
.flex-row{
         ^
      Invalid CSS after ".flex-row{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/layout.scss (line 5, column 11)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-f9ed1666","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/layout.scss 4:14-502
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-aa3a9102","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/layout.scss
Module build failed:
.flex-row{
         ^
      Invalid CSS after ".flex-row{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/layout.scss (line 5, column 11)
Error:
.flex-row{
         ^
      Invalid CSS after ".flex-row{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/layout.scss (line 5, column 11)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-aa3a9102","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/layout.scss 4:14-502
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-f9ed1666","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/searchbar.scss
Module build failed:
.bui-searchbar{
              ^
      Invalid CSS after ".bui-searchbar{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/searchbar.scss (line 5, column 16)
Error:
.bui-searchbar{
              ^
      Invalid CSS after ".bui-searchbar{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/searchbar.scss (line 5, column 16)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-f9ed1666","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/searchbar.scss 4:14-505
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-aa3a9102","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/searchbar.scss
Module build failed:
.bui-searchbar{
              ^
      Invalid CSS after ".bui-searchbar{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/searchbar.scss (line 5, column 16)
Error:
.bui-searchbar{
              ^
      Invalid CSS after ".bui-searchbar{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/searchbar.scss (line 5, column 16)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-aa3a9102","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/searchbar.scss 4:14-505
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-50835d06","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/slider-bar.scss
Module build failed:
.bui-slider-bar{
               ^
      Invalid CSS after ".bui-slider-bar{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/slider-bar.scss (line 3, column 17)
Error:
.bui-slider-bar{
               ^
      Invalid CSS after ".bui-slider-bar{": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/slider-bar.scss (line 3, column 17)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-50835d06","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/slider-bar.scss 4:14-506
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-913ae494","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/tabbar.scss
Module build failed:
.bui-tabbar-wrapper {
                    ^
      Invalid CSS after "...abbar-wrapper {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/tabbar.scss (line 3, column 22)
Error:
.bui-tabbar-wrapper {
                    ^
      Invalid CSS after "...abbar-wrapper {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/tabbar.scss (line 3, column 22)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-913ae494","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/tabbar.scss 4:14-502
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-5e3c56fa","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/tabbar.scss
Module build failed:
.bui-tabbar-wrapper {
                    ^
      Invalid CSS after "...abbar-wrapper {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/tabbar.scss (line 3, column 22)
Error:
.bui-tabbar-wrapper {
                    ^
      Invalid CSS after "...abbar-wrapper {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/tabbar.scss (line 3, column 22)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-5e3c56fa","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/tabbar.scss 4:14-502
/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-3569fe35","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/tip.scss
Module build failed:
.tip {
     ^
      Invalid CSS after ".tip {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/tip.scss (line 3, column 7)
Error:
.tip {
     ^
      Invalid CSS after ".tip {": expected "}", was "{"
      in /Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/bui-weex/src/css/tip.scss (line 3, column 7)
    at options.error (/Users/m/Documents/Macula_Mobile/cenarius-weex-project/node_modules/node-sass/lib/index.js:291:26)
 @ /usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-style-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/css-loader!/usr/local/lib/~/weex-toolkit/~/weex-previewer/~/weex-builder/~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-3569fe35","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?indentedSyntax!./~/bui-weex/src/css/tip.scss 4:14-499

**Comment by tonyyls** [comment]
请确保 node-sass,sass-loader 正常安装，上面的错误就是 sass的原因，另外 webpack.config.js里面注意配置loader
`{
      test: /\.scss$/,
      loader: 'style!css!sass'
}`

**Comment by myeveryheart** [comment]
已经按要求正确配置。
我担心的是使用命令：
weex App.vue
weex-toolkit有自己的一套webpack配置，并不会读取本项目的。

**Comment by tonyyls** [comment]
bui-weex的模版工程最后会在dist目录下生成对应的bundle（只到这一步），weexpack如果不是读取这里的，可以考虑手动拷贝的方式到 它的工程。
