### ISSUE TITLE
打包后的js太大 一个js文件500KB 压缩后也有250KB

### ISSUE THREAD

**Issue by jewool** [bingo-oss/bui-weex#3]
框架刚出来，正在优化过程中。感谢关注！

**Comment by tonyyls** [comment]
目前一个 js大概200多k，原因是里面的字体文件在decode的时候用了 he.js，引入它本身就85k。 正在尝试优化，后续由结果会告知。

**Comment by tonyyls** [comment]
请看这个 [commit](https://github.com/bingo-oss/bui-weex/commit/1bba4e62b7ca38c92ff0b34208f6a6175630fbfe) 已经去掉了对he的依赖
