### ISSUE TITLE
本地图片和字体图标在安卓模拟器中不能显示

### ISSUE THREAD

**Issue by yangdm2015** [bingo-oss/bui-weex#31]
`http://photo-shany.oss-cn-beijing.aliyuncs.com/%E7%B2%98%E8%B4%B4%E5%9B%BE%E7%89%87.png`
`http://photo-shany.oss-cn-beijing.aliyuncs.com/2.png`
在playground里都是可以正常显示的，打包放到android studio里就不正常了

**Comment by tonyyls** [comment]
问题已知，谢谢反馈，我们会尽快修复

**Comment by sun2013** [comment]
这问题我也碰到了， 解决了没哟

**Comment by tonyyls** [comment]
抱歉，因我们的app放在非asset目录下，此bug一直未修复。 目前以及修复。 请看 [ commit ](https://github.com/bingo-oss/bui-weex/commit/c95ed5aa68f744d80a175d2822d05761f40215d7)

**Comment by tonyyls** [comment]
已经修复。 see [commit](https://github.com/bingo-oss/bui-weex/commit/c95ed5aa68f744d80a175d2822d05761f40215d7)

**Comment by wyanhui02** [comment]
我用了最新的代码，怎么还是无法显示字体图标，虚拟器和真机都显示不了。

**Comment by wyanhui02** [comment]
安卓的
