### ISSUE TITLE
新创建的工程启动正常 但是用Playground扫描什么都没有

### ISSUE THREAD

**Issue by Kratos2** [bingo-oss/bui-weex#33]
新创建的工程启动正常 但是用Playground扫描什么都没有

**Comment by tonyyls** [comment]
使用debug模式观察下哪里报错？

**Comment by Kratos2** [comment]
不报错但是 source里面没有app.js

**Comment by Kratos2** [comment]
完全按照流程做的 。。。

**Comment by tonyyls** [comment]
这边按照步骤：
1. bui-weex create demo
2.cd demo  && npm install
3. npm run dev
4. npm run serve 
正常哦。
请检查：
1.saas 相关依赖是否安装成功，特别是node sass；
2.框架入口在 src/entry/app.js 无 source 目录；
3.再次检查下终端命令行，chrome控制台有没其他异常信息

**Comment by tonyyls** [comment]
检查下phone 和 pc  是否处于同一局域网，否则无法访问

**Comment by Kratos2** [comment]
控制台在执行npm run dev
 是不是不会自动结束，需要control+c来结束呢？

**Comment by Kratos2** [comment]
okLe
