### ISSUE TITLE
是weex版本有要求吗？

### ISSUE THREAD

**Issue by ydlds** [bingo-oss/bui-weex#40]
是weex版本有要求吗？我的是最新的weex，无法使用！

**Comment by ZhijianZhang** [comment]
npm run dev 和 npm run serve 之后 在 8686 端口运行的weex.html 请求的应该是 `  <script src="./dist/app.weex.js"></script>
` 而不是 `  <script src="./dist/app.web.js"></script>
` 吧？ `app.web.js` 一直报 404 错误的，dist目录下没有这个文件
