### ISSUE TITLE
npm run serve 报错

### ISSUE THREAD

**Issue by yin2017168** [bingo-oss/bui-weex#44]
D:\test-demo>npm run serve

> bui-weex-template@1.0.7 serve D:\test-demo
> node build/init.js && serve -p $npm_package_ports_serverPort

net.js:1483
      throw new RangeError('"port" argument must be >= 0 and < 65536');
      ^

RangeError: "port" argument must be >= 0 and < 65536
    at Server.listen (net.js:1483:13)
    at Function.app.listen (D:\test-demo\node_modules\serve\node_modules\connect\lib\proto.js:229:24)
    at Object.<anonymous> (D:\test-demo\node_modules\serve\bin\serve:132:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bui-weex-template@1.0.7 serve: `node build/init.js && serve -p $npm_package_ports_serverPort`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bui-weex-template@1.0.7 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by liyueqing** [comment]
package.json文件里的‘$npm_package_ports_serverPort’这个指向配置问题，severPort这个参数设置，范围是‘>= 0 and < 65536’，如下图，你看看是否有效。
![wechatimg670](https://user-images.githubusercontent.com/29270353/38477393-ee430c84-3b77-11e8-858c-860fd38661d2.jpeg)

**Comment by yin2017168** [comment]
就是默认不行，改课几个，怎么改都一样的错
端口号就是在这个范围，无论怎么设置都没用，有没被占用

**Comment by gendseo** [comment]
不知道你的 weex 和 weex create demo的是什么版本
我的是在项目文件夹下demo/configs/config.js这个文件下改port就行

**Comment by yin2017168** [comment]
@gendseo
你用的是bui-weex这个UI框架不

**Comment by yin2017168** [comment]
我的weex是最新的v1.2.9

**Comment by gendseo** [comment]
我是自己写的ui

**Comment by gendseo** [comment]
bui-weex 恕在下直言，bug还很多，要用到生产环境需谨慎些

**Comment by liyueqing** [comment]
在windows环境不支持$npm_package_ports_serverPort语法，另外要升级下相关的依赖包。

**Comment by liyueqing** [comment]
在windows环境不支持$npm_package_ports_serverPort语法，另外要升级下相关的依赖包。最新的版本已经修复你的问题@yin2017168
