### ISSUE TITLE
bui-weex 打包生成的publish文件， 如何跟weex结合生成apk安装应用

### ISSUE THREAD

**Issue by dq095** [bingo-oss/bui-weex#48]
我是初学者，看了您的框架，然后做出一个小Demo，之后想打包生成apk，在您的文档中只看到这么一段话话【运行 publish 命令，该命令会从dist目录中抽取出提供给 android 和 iOS平台用的 Bundle资源 。在工程根目录下生成 publish 文件夹(只保留了 *.weex.js)】，之后具体如何生成apk找不到啊，与weex 生成的android结合吗，还是？？？ 网上搜索不到相应的答案，晕，求助！！！

**Comment by tonyyls** [comment]
bui-weex 只是UI层面的，publish 后会产生个 bundle js（dist） ,把这些资源文件放到weex容器里面即可
