### ISSUE TITLE
[优化]使用he.js对字体文件进行decode导致打出来对包体积太大

### ISSUE THREAD

**Issue by tonyyls** [bingo-oss/bui-weex#5]
bui-icon使用he.js进行decode，引入这个he.js大概85k。打出来对包多了很多。看能否寻找替代方案

**Comment by bugstark** [comment]
可以去掉icon吧，用户可以自己使用iconfont来自己生成，体积也小

**Comment by tonyyls** [comment]
可以的。 目前有些组件内部也用到了bui-icon，所以在去掉icon的时候请注意下相关组件也要处理。例如,bui-header, bui-tabbar 等。

**Comment by Spikef** [comment]
#22

**Comment by tonyyls** [comment]
[this commit](https://github.com/bingo-oss/bui-weex/commit/1bba4e62b7ca38c92ff0b34208f6a6175630fbfe)
去掉对he的依赖。正则配合String.fromCharCode优化该问题
