### ISSUE TITLE
通过 Vue plugin方式注入到全局的方法，如何开启代码智能提示？

### ISSUE THREAD

**Issue by ef100** [bingo-oss/bui-weex#50]
"bui-weex无需显式引用，通过 Vue plugin方式注入到全局；"
通过 Vue plugin方式注入到全局的方法，如何开启代码智能提示？

比如我现在用的是VSCode就无法自动感知到注入的方法

**Comment by tonyyls** [comment]
这个暂时没比较好的办法，做成plugin 是为了更方便调用，尚未考虑 代码提示的问题。
