### ISSUE TITLE
按钮状态无法动态切换

### ISSUE THREAD

**Issue by shaokunpeng** [bingo-oss/bui-weex#54]
使用disabled属性控制按钮启用或禁用，发现第一次从启用到禁用可以，之后就处于禁用状态，发现原因是计算字段exBtnStyle有问题，参考代码如下：
exBtnStyle () {
        const {type, disabled, btnStyle} = this;
        const exBtnStyle = Object.assign(STYLE_MAP[type], btnStyle);
        return disabled ? Object.assign({},exBtnStyle, {
          backgroundColor: 'rgba(0, 0, 0, 0.1)',
          borderWidth: 0
        }) : exBtnStyle;
      }

**Comment by liyueqing** [comment]
0.3.2版本已经解决该问题，感谢你的支持，使用过程有问题欢迎来撩。

**Comment by liyueqing** [comment]
0.3.2版本已经解决该问题，感谢你的支持，使用过程有问题欢迎来撩。
