### ISSUE TITLE
如何使用呀？

### ISSUE THREAD

**Issue by Ahuangshang** [bingo-oss/bui-weex#7]
你这个效果看着挺好的，也有功能也是我想要的，但是我怎么样才能用呀

**Comment by tonyyls** [comment]
请移步官网 http://dev.bingocc.com/buiweex  ，仔细看入门，从环境开始。 需要有weex开发基础。

**Comment by Ahuangshang** [comment]
看了你们的文档了，还是不会使用，weex官网是能把 .vue 文件通过weex compile 变成 .js 文件，用了这个就不能这样了，那我该如何加载呢？手机上没法显示的

**Comment by tonyyls** [comment]
weex官方告诉我们运行`npm run dev` 可以在 dist目录下生成对应的bundle js，这就是你要用的js了。`npm run serve` 帮你启动了serve，并且把js部署起来，用 playground 扫描就可以看到效果。weex官方 都是这么做的， 通常不会直接用 weex compile 去做事的 。请看看：http://weex-project.io/cn/guide/set-up-env.html 。  另外，这是v2.x的文档。

**Comment by Ahuangshang** [comment]
我按照你们官方的说明新建了个工程，但是运行npm run dev 时发现
> bui-weex-template@1.0.0 dev D:\workeSpace\buiWeex
> webpack --watch

'webpack' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bui-weex-template@1.0.0 dev: `webpack --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bui-weex-template@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2017-07-31T03_30_45_
594Z-debug.log
为什么工程都运行不了？
