### ISSUE TITLE
tabbar-demo.vue 多次刷新 后 第一个tab数据会与第三个tab重叠

### ISSUE THREAD

**Issue by cableyang** [bingo-oss/bui-weex#9]
tabbar-demo 点击刷新  大约是5次会出现一次 首页与我的页面数据重叠  原生页面debug看到index 错乱了

**Comment by tonyyls** [comment]
请告知系统、手机型号？这边测试暂时未出现类似现象。 用的playground 是官网的。

**Comment by cableyang** [comment]
测试手机为nexus5 android 7.1 以及Redmi note3 android5.1 
若发现重复刷新时，发现 后续的tab覆盖问题，此时使用append="tree",可避免此问题
